# Termination Signals
FederationRounds: 3 # only in synchronous execution
ExecutionCutoffTimeMins: 100000
EvaluationMetric: "accuracy" # Others are "accuracy", "loss"
EvaluationMetricCutoffScore: 1

# CommunicationProtocol
CommunicationProtocol: "Synchronous"
EnableSSL: false

# ModelStore 
ModelStore: "InMemory" # Others are "InMemory", "Redis"
ModelStoreHostname: "localhost"
ModelStorePort: 6379
EvictionPolicy: "LineageLengthEviction" # Others are "NoEviction", "LineageLengthEviction"
LineageLength: 1 # This field is only applicable if EvictionPolicy is set to "LineageLengthEviction"

# # homomorphic encryption scheme - if provided run with it, else disabled.
HEScheme: "CKKS" # Others are "CKKS" (a fully-homomorphic encryption scheme).
HEBatchSize: 4096
HEScalingBits: 52

# GlobalTrainingConfig:
AggregationRule: "PWA" # Others are FedAvg, FedStride, FedStride, PWA
ScalingFactor: "NumTrainingExamples"
ParticipationRatio: 1

# LocalTrainingConfig:
BatchSize: 32
LocalEpochs: 4
ValidationPercentage: 0.0
Optimizer: "VanillaSGD" # Others are "Adam", "RMSProp"
OptimizerParams:
  learning_rate: 0.01

# ControllerConfig:
Controller:
  ProjectHome: "/metisfl"
  Hostname: "localhost"
  Username: "root"
  Password: "root"
  OnLoginCommand: "source /etc/profile;"
  GRPCServicerHostname: "localhost"
  GRPCServicerPort: 50051
  SSLPrivateKey: "/metisfl/metisfl/resources/ssl_config/default/server-key.pem"
  SSLPublicCertificate: "/metisfl/metisfl/resources/ssl_config/default/server-cert.pem"

# LearnersConfig:
Learners:
  - ProjectHome: "/metisfl"
    Hostname: "localhost"
    Username: "root"
    Password: "root"
    OnLoginCommand: "source /etc/profile;"
    GRPCServicerHostname: "localhost"
    GRPCServicerPort: 50052
    CudaDevices: [0]