# EnvironmentConfig:
FederationRounds: 3 # only in synchronous execution
ExecutionCutoffTimeMins: null
MetricCutoffScore: 1.0
CommunicationProtocol: "Synchronous"
EnableSSL: False

ModelStore: "InMemory" # Others are "InMemory", "Redis"
ModelStoreHostname: "" # This field is only applicable if ModelStore is set to "Redis"
ModelStorePort: 6379 # This field is only applicable if ModelStore is set to "Redis"

EvictionPolicy: "LineageLengthEviction" # Others are "NoEviction", "LineageLengthEviction"
LineageLength: 1 # This field is only applicable if EvictionPolicy is set to "LineageLengthEviction"

# homomorphic encryption scheme - if provided run with it, else disabled.
HEScheme: "CKKS" # Others are "CKKS" (a fully-homomorphic encryption scheme).
HEBatchSize: 4096
HEScalingBits: 52

# GlobalTrainingConfig:
AggregationRule: "FedAvg" # Others are FedAvg, FedStride, FedRec, PWA
ScalingFactor: "NumTrainingExamples" # Others are NUM_COMPLETED_BATCHES, NUM_PARTICIPANTS, NUM_TRAINING_EXAMPLES
ParticipationRatio: 1

# LocalTrainingConfig:
BatchSize: 32
EvaluationMetric: "accuracy"
LocalEpochs: 4
ValidationPercentage: 0.0
Optimizer: "VanillaSGD" # Others are "MomentumSGD", "Adam", "RMSProp"
OptimizerParams:
  learning_rate: 0.01

# ControllerConfig:
Controller:
  ProjectHome: "/home/panoskyriakis/metisfl"
  ConnectionConfigs:
    Hostname: "localhost"
    Username: "panoskyriakis"
    KeyFilename: "/home/panoskyriakis/.ssh/id_rsa"
    OnLogin: "source /etc/profile;"
  GRPCServicer:
    Hostname: "localhost"
    Port: 50051

# LearnersConfig:
Learners:
  - LearnerID: "localhost-1"
    ProjectHome: "/home/panoskyriakis/metisfl"
    ConnectionConfigs:
      Hostname: "localhost"
      Username: "panoskyriakis"
      KeyFilename: "/home/panoskyriakis/.ssh/id_rsa"
      OnLogin: "source /etc/profile;"
    GRPCServicer:
      Hostname: "localhost"
      Port: 50052
    CudaDevices: [0]

